//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "commentary")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub match_id: i32,
    pub minute: Option<i32>,
    pub sequence: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub period: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub event_type: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub actor: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub team: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub message: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    pub tags: Option<Vec<String>>,
    pub created_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "match_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub matches: BelongsTo<super::matches::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
