//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::MatchStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "matches")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub sport: String,
    #[sea_orm(column_type = "Text")]
    pub home_team: String,
    #[sea_orm(column_type = "Text")]
    pub away_team: String,
    pub status: MatchStatus,
    pub start_time: DateTime,
    pub end_time: DateTime,
    pub home_score: i32,
    pub away_score: i32,
    pub created_at: DateTime,
    #[sea_orm(has_many)]
    pub commentaries: HasMany<super::commentary::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
